remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Enkidu Mods
author: Enkidu
description: Hello, I'm Enkidu, a passionate Sims 4 player and modder. This page is a collection of my smaller mods that I've created to enhance my own Sims 4 gaming experience. Some are recent fixes, others are tweaks I've used for years, and a few are works in progress with some functioning features. While these mods are pulled directly from my in-game Mods folder and may be unfinished or contain bugs, you're welcome to download and explore them at your own discretion. Enjoy the mods and happy Simming!

logo: /assets/img/enkidu_pfp_300x300.png
