remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Enkidu Mods
author: Enkidu
description: Enkidu's personal collection of Sims 4 mods, enhancing gameplay one tweak at a time.

logo: /assets/img/enkidu_pfp_300x300.png
