remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Enkidu Mods
author: Enkidu
description: Page for some of my smaller mods
